### ISSUE TITLE
Android example build failed

### ISSUE THREAD

**Issue by mchriss** [zaptrem/react-native-transcription#2]
Hello!
After running yarn bootstrap and yarn example android commands I get the following console error:

```
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
> Exception java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache [in thread "Daemon worker"]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 881ms

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

error Command failed with exit code 1.
```

Tried running it with both an emulator and a connected device, but got the same results.
Any idea how to fix this?

Thanks!

**Comment by zaptrem** [comment]
It appears Android Studio can't find your phone or VM: `No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...`

**Comment by mchriss** [comment]
> 

I managed to fix the AVD issue, but the ```java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache [in thread "Daemon worker"]``` exception still remains.

**Comment by mchriss** [comment]
Okay, this was caused by a Gadle + Java version bug, after I fixed those I managed to get the app running
